// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv5kFdUd1SXwM8DNbHwrKhDL_Ku7_G7Rk',
    appId: '1:824674209913:web:697da96301c9854e4744a8',
    messagingSenderId: '824674209913',
    projectId: 'capstone-mobile-app-375221',
    authDomain: 'capstone-mobile-app-375221.firebaseapp.com',
    storageBucket: 'capstone-mobile-app-375221.appspot.com',
    measurementId: 'G-H60PQM6FPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlHAe_57Mla_ZlZVVi2EwKSfxNuZe8wKg',
    appId: '1:824674209913:android:3aa2037103d643024744a8',
    messagingSenderId: '824674209913',
    projectId: 'capstone-mobile-app-375221',
    storageBucket: 'capstone-mobile-app-375221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPQULN53II-k4wMDMoV5TjiZK4KHnNB1c',
    appId: '1:824674209913:ios:88730eaa7c928a484744a8',
    messagingSenderId: '824674209913',
    projectId: 'capstone-mobile-app-375221',
    storageBucket: 'capstone-mobile-app-375221.appspot.com',
    iosClientId: '824674209913-3b06jeqcpfmqkal6mo9hif676cp9lki4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPQULN53II-k4wMDMoV5TjiZK4KHnNB1c',
    appId: '1:824674209913:ios:88730eaa7c928a484744a8',
    messagingSenderId: '824674209913',
    projectId: 'capstone-mobile-app-375221',
    storageBucket: 'capstone-mobile-app-375221.appspot.com',
    iosClientId: '824674209913-3b06jeqcpfmqkal6mo9hif676cp9lki4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
